
SELECT 
       SERVERPROPERTY('BuildClrVersion') BuildClrVersion,
       SERVERPROPERTY('Collation') Collation, 
       SERVERPROPERTY('CollationID') CollationID,
       SERVERPROPERTY('ComparisonStyle') ComparisonStyle,
       SERVERPROPERTY('ComputerNamePhysicalNetBIOS') ComputerNamePhysicalNetBIOS,
       SERVERPROPERTY('Edition') Edition,
       SERVERPROPERTY('EditionID') EditionID,
       SERVERPROPERTY('EngineEdition') EngineEdition,
       SERVERPROPERTY('InstanceName') InstanceName,
       SERVERPROPERTY('IsClustered') IsClustered,
       SERVERPROPERTY('IsFullTextInstalled') IsFullTextInstalled,
       SERVERPROPERTY('IsIntegratedSecurityOnly') IsIntegratedSecurityOnly,
       SERVERPROPERTY('IsSingleUser') IsSingleUser,
       SERVERPROPERTY('LCID') LCID,
       SERVERPROPERTY('LicenseType') LicenseType,
       SERVERPROPERTY('MachineName') MachineName,
       SERVERPROPERTY('NumLicenses') NumLicenses,
       SERVERPROPERTY('ProcessID') ProcessID,
       SERVERPROPERTY('ProductVersion') ProductVersion,
       SERVERPROPERTY('ProductLevel') ProductLevel,
       SERVERPROPERTY('ResourceLastUpdateDateTime') ResourceLastUpdateDateTime,
       SERVERPROPERTY('ResourceVersion') ResourceVersion,
       SERVERPROPERTY('ServerName') ServerName,
       SERVERPROPERTY('SqlCharSet') SqlCharSet,
       SERVERPROPERTY('SqlCharSetName') SqlCharSetName,
       SERVERPROPERTY('SqlSortOrder') SqlSortOrder,
       SERVERPROPERTY('SqlSortOrderName')SqlSortOrderName
		
